### ISSUE TITLE
How to get REDSTONE DUST

### ISSUE THREAD

**Issue by wolfieboy09** [tom5454/Create-Ore-Excavation#81] opened 2024-02-22 17:01 UTC
So once I obtain `Raw Redstone`, how do I cook it

**Comment by tehmilcho** [comment] 2024-03-12 11:48
Regarding to recipets it should be work by milling 

![image](https://github.com/tom5454/Create-Ore-Excavation/assets/22918349/14296daa-1adf-499d-87ff-1394223bdd01)

But its not working by for me .. the Mill will accept the Item but will not something with it.

**Comment by tehmilcho** [comment] 2024-03-12 12:26
It seems to work fine with Crushing Wheels .. there no recipets shown for .. but i tested it and its working for me

**Comment by tom5454** [comment] 2024-03-25 18:16
Duplicate of #74

**Closed by tom5454** 2024-03-25 18:16 UTC
